/**
 * personas.ts — the fixed cast of the live run: the four test apps A–D, the
 * three channels, and the names the testplan (testplans/b.yko) uses for them.
 *
 * Pure constants and derivations; no I/O.
 */

export const PERSONA_LETTERS = ['a', 'b', 'c', 'd'] as const
export type PersonaLetter = (typeof PERSONA_LETTERS)[number]

/** Slack channel names must be lowercase: the plan's "A-home" / "D-home" are these. */
export const CHANNEL_NAMES = ['a-home', 'coordination', 'd-home'] as const
export type ChannelName = (typeof CHANNEL_NAMES)[number]

/** Which channels each persona's bot user is invited to (C is in none). */
export const CHANNEL_MEMBERSHIP: Record<PersonaLetter, readonly ChannelName[]> = {
  a: ['a-home', 'coordination'],
  b: ['coordination'],
  c: [],
  d: ['d-home'],
}

/** The app name and bot display name: "CSCB Test A" … "CSCB Test D". */
export function appDisplayName(letter: PersonaLetter): string {
  return `CSCB Test ${letter.toUpperCase()}`
}

/** The persona name in config.json: `persona_a` … `persona_d`. */
export function personaName(letter: PersonaLetter): string {
  return `persona_${letter}`
}

/** The credentials file's base name, as the testplan names it. */
export function credentialsFileName(letter: PersonaLetter): string {
  return `persona_${letter}-credentials.json`
}

/** The name of the app-level token the runner generates for Socket Mode. */
export const APP_TOKEN_NAME = 'cscb-live'

/** The name of B's second app-level token, generated by Check 28. */
export const ROTATED_APP_TOKEN_NAME = 'cscb-live-rotated'
